### PR TITLE
feat: convert to Angular CLI project structure for library and app

### PR DESCRIPTION
**Pull request by ColinMorris83**
- Converted over to be built with Angular CLI
- Fix for #580

### CODE REVIEW

**Comment by NepipenkoIgor** [comment]
@ColinMorris83  We had some logic updates and some changes in doc . Could you check and maybe change you PR ?

**Comment by ColinMorris83** [comment]
> @ColinMorris83 We had some logic updates and some changes in doc . Could you check and maybe change you PR ?

Sure, no problem, is updated now.

**Comment by NepipenkoIgor** [comment]
@ColinMorris83 it seems some conflicts

**Comment by ColinMorris83** [comment]
> @ColinMorris83 it seems some conflicts

@NepipenkoIgor is is actually going to get merged if I do this latest merge of develop? As it's getting quite time consuming to keep manually taking in all the changes on other PR's

**Comment by NepipenkoIgor** [comment]
@ColinMorris83 Please fix and we will merge

**Comment by ColinMorris83** [comment]
> @ColinMorris83 Please fix and we will merge

ok, will wait until the changelog and package files are updated for 8.1.3 before I merge.

**Comment by ColinMorris83** [comment]
Any update on the above, is there going to be an 8.1.3 published?

**Comment by NepipenkoIgor** [comment]
@ColinMorris83 its seems like 8.1.2 latest

**Comment by ColinMorris83** [comment]
> @ColinMorris83 its seems like 8.1.2 latest

But surely an 8.1.3 is needed for these changes: https://github.com/JsDaddy/ngx-mask/pull/600/files

**Comment by NepipenkoIgor** [comment]
its merged and published

**Comment by ColinMorris83** [comment]
> its merged and published

what is? 8.1.2 was published 11 days ago, there have been bug fixes merged to develop branch since then, I have been waiting for them to get published as 8.1.3 before merging in and updating my version to 8.1.4

**Comment by NepipenkoIgor** [comment]
@ColinMorris83  Done . The latest published

**Comment by ColinMorris83** [comment]
> @ColinMorris83 Done . The latest published

Ok, have merged and updated package files to 8.1.4 and updated changelog to also include 8.1.3 change

**Pull request merged**
