### PR TITLE
.map of undefined

### PR DESCRIPTION
**Pull request by pfrendo**
There are still issues on the config when AOT'd

### CODE REVIEW

**Comment by pfrendo** [comment]
@NepipenkoIgor

**Comment by caseyPav** [comment]
https://github.com/vgildeev/ngx-mask/commit/064a071716a5c433c07d4091de696fa170a49059 

@pfrendo This is perhaps a slightly more robust solution... Tested working for me but need to wait for it or something similar get merged upstream as I'm not running one of my project deps off of a fork and this is sadly the best suited module for my needs.

Badly need to make the jump to angular 5... Unsure how/why previous AOT fix for closed bug actually works... I've had zero success with it regardless of configuration.

**Comment by pfrendo** [comment]
@caseyPav , I am working on a long term solution..

**Comment by pfrendo** [comment]
Agreed it looks good :)

**Pull request closed without merging**
