### PR TITLE
Add property shown mask auto position

### PR DESCRIPTION
**Pull request by Fafnur**
Added feature which add a new property called "showMaskAutoPosition". This property override current posStart, posEnd on MaskDirective with enabled property 'showMaskTyped'.
Added example to app.component.

### CODE REVIEW

**Comment by isysenko** [comment]
@Fafnur Please resolve merge conflicts

**Comment by Fafnur** [comment]
@isysenko I merged, but now, there are ci build errors. Is it ok?

**Comment by isysenko** [comment]
@Fafnur merge develop into your branch one more time please

**Comment by Thegrep01** [comment]
@Fafnur Please resolve merge conflicts

**Comment by Fafnur** [comment]
@Thegrep01 I think, the last version of the ngx-mask does not need a pull request, because 
last version works like as "auto position"

**Pull request closed without merging**
