### PR TITLE
aot config fixes

### PR DESCRIPTION
**Pull request by pfrendo**
This PR is fixing issues when it comes to config with AOT also the fact that the set initialization has to be in a function as well otherwise it will also break when AOT'ed

### CODE REVIEW

**Comment by pfrendo** [comment]
@LimarenkoDenis - Could you please check this? As I need this urgently !

**Comment by NepipenkoIgor** [comment]
Hi, it is awesome. I will check and publish all things tomorrow.

**Comment by pfrendo** [comment]
@NepipenkoIgor Thanks !

**Comment by pfrendo** [comment]
@NepipenkoIgor will this be merged today? As I am dependent on it :)

**Comment by NepipenkoIgor** [comment]
Done

**Comment by digitalmedia34** [comment]
I know there was a commit for a fix but can anyone say if its fixed? I am having the same issue with version 2.1.17

**Comment by digitalmedia34** [comment]
I am able to replicate the issue by running ng build --prod

**Pull request merged**
