### PR TITLE
fix(mask.directive.ts): parse input as a number if  maskvalue starts with 'separator'

### PR DESCRIPTION
**Pull request by leandroneves-net**
My server sends numeric values as javascrpt strings. So if separator
mask is used the input string will be treated as a NumberValue.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/JsDaddy/ngx-mask/blob/develop/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
Strings are parsed incorrectly when we are working with "separator"

Issue Number: 948

## What is the new behavior?
Strings will be trated as a NumberValue.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by NepipenkoIgor** [comment]
@leandroneves-net  Hi. Could you add test around this issue

**Comment by leandroneves-net** [comment]
Hello Igor,

I don't know how to write tests. Could you send me a sample or a paper?

Best regards,

Leandro

Em sáb., 27 de nov. de 2021 às 21:50, Igor Nepipenko <
***@***.***> escreveu:

**Comment by NepipenkoIgor** [comment]
@leandroneves-net  could you check this section of library https://github.com/JsDaddy/ngx-mask/tree/develop/projects/ngx-mask-lib/src/test .

**Comment by NepipenkoIgor** [comment]
Also please pay attention that we migrated to angular 13. You need to install deps and make reverse merge fro develop

**Comment by leandroneves-net** [comment]
Igor,

I read the tests files and made 2 test files. 

The first, on "separator.psec.js", has no effects. Propabily it is redundant, because I decided explicitly declare decimalMarker. The second, on dynamic.specs.ts reflets the new behavor.

I'm using angular 13 and commited no changes to others files to avoid "breaks" on the code..

Best regards,

Leandro

**Pull request closed without merging**
