### PR TITLE
feat(1079): patch fix #1069 into 14.2 version for compatibility

### LINKED ISSUE #1069: Input seleciontStart goes to wrong position after dynamic mask changes while typing
# 🐞 bug report

### Is this a regression?
No

### Description

Using dynamic mask (mask composed by two masks), when it changes from to smaller mask to the bigger one, the caret position (selectionStart) doesn't go to the end on the input, it stays on the middle of it, on the old position.

## 🔬 Minimal Reproduction
Editor:
https://stackblitz.com/edit/angular-ivy-mask-dynamic-issue?file=src%2Fapp%2Fapp.component.html

Browser:
https://angular-ivy-mask-dynamic-issue.stackblitz.io/

## 🔥 Exception or Error

Reproduction

## 🌍 Your Environment

**Angular Version:**

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.17
Node: 16.19.0 (Unsupported)
Package Manager: npm 8.19.3
OS: linux x64

Angular: 12.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.14
@angular-devkit/build-angular   12.2.14
@angular-devkit/core            12.2.14
@angular-devkit/schematics      12.2.17
@angular/cli                    12.2.17
@schematics/angular             12.2.17
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**
ngx-mask version: 15.0.2

### PR DESCRIPTION
**Pull request by mikaelboff**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/JsDaddy/ngx-mask/blob/develop/CONTRIBUTING.md#commit
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information
Issue related: #1079
 
I'm creating this pull request to patch the Fix (https://github.com/JsDaddy/ngx-mask/issues/1069) into version 14.2 and create version 14.2.5.

The reason to this is to maintain compatibility for projects with angular version < 14, since [This commit](https://github.com/mikaelboff/ngx-mask/commit/fc9c262f0a751ebc1d772cfe500cf1529f03f094#diff-9556503b7e3692c9f1b317e27dac8e2740d9c1a0d19c083dda59d9328a09a2d3) has changed the peer dependencies of angular version to >=14.0.0.

### CODE REVIEW

**Comment by mikaelboff** [comment]
Hi, can you review this, please? @NepipenkoIgor

**Comment by mikaelboff** [comment]
@andriikamaldinov1 @NepipenkoIgor could you guys please consider this?

**Comment by NepipenkoIgor** [comment]
@mikaelboff  Thank you for this patch . But as i remember we added fixes for later versions. We don't have strategy in this moment to have LTS or something like this. Its mean that we care about latest releases and adopting ngx-mask to latest versions of angular. In general for ng14 we could use ngx-mask > 15.0.0  that include your fix . The main difference that for delivery ngx-mask we will not using ngModule any more

**Comment by NepipenkoIgor** [comment]
@mikaelboff  if you agree please close PR and issues relative to it . And we will waiting you contributing in future

**Comment by mikaelboff** [comment]
> @mikaelboff Thank you for this patch . But as i remember we added fixes for later versions. We don't have strategy in this moment to have LTS or something like this. Its mean that we care about latest releases and adopting ngx-mask to latest versions of angular. In general for ng14 we could use ngx-mask > 15.0.0 that include your fix . The main difference that for delivery ngx-mask we will not using ngModule any more

The main reason I'm requesting this patch is to an application with Angular version < 14. Updating the application source to adapt to new versions would cost me a lot; but if there's no chance of patching the fix with these merge request, I'll have to close it, fork the lib and apply the patch myself, until there's time to upgrade the source code of my application to use > 14 angular version. There isn't really any little chance of patching/publishing on npm?

**Pull request closed without merging**
