### PR TITLE
fix: fix ngx-mask lib to be able to use it in AoT mode

### PR DESCRIPTION
**Pull request by pfrendo**

### CODE REVIEW

**Comment by pfrendo** [comment]
@vgildeev - I have confirmed it is working, so I opened it for you. Can @NepipenkoIgor review and merge it if valid?

**Comment by vgildeev** [comment]
Thank you @pfrendo :)

**Comment by caseyPav** [comment]
@pfrendo @vgildeev thanks to you both, also can confirm this works.

Would appreciate @Nepipenkolgor taking a look at it when possible- preventing bumping project to angular 5.

**Comment by ThalesMatoso** [comment]
It's work! Thank You

**Comment by NepipenkoIgor** [comment]
@pfrendo I will try to do this before weekend

**Comment by caseyPav** [comment]
@Nepipenkolgor sorry to pester but any estimate as to when these changes will be reviewed?

**Pull request merged**
