### PR TITLE
Add dynamic mask and CPF_CNPJ pattern

### PR DESCRIPTION
**Pull request by claudiotrindade**
fix issue #365 
fix issue #172

### CODE REVIEW

**Comment by NepipenkoIgor** [comment]
@claudiotrindade Please add tests

**Comment by claudiotrindade** [comment]
@NepipenkoIgor Please check it's ok

**Comment by samuelrvg** [comment]
@NepipenkoIgor check it's ok

**Comment by martinsware** [comment]
Hi!

Is there a possibility to add a backward compatibility of this feature with the angular 8?

if so, I have already made the necessary changes in
https://github.com/martinsware/ngx-mask/tree/feat/720-angular8

Thanks in advance!

**Comment by matheusjordan** [comment]
Muito obrigado por essa implementação, essa mascara é de grande valia em diversos projetos no Brasil, gratidão!

**Pull request merged**
